java -jar dist/Compiler.jar TreeVisitor.java
java -jar dist/Compiler.jar Test.java
java -jar dist/Compiler.jar QuickSort.java
java -jar dist/Compiler.jar LinkedList.java
java -jar dist/Compiler.jar LinearSearch.java
java -jar dist/Compiler.jar Factorial.java
java -jar dist/Compiler.jar BubbleSort.java
java -jar dist/Compiler.jar BinaryTree.java
java -jar dist/Compiler.jar BinarySearch.java