package compiler;

/* Generated By:JavaCC: Do not edit this line. MiniJavaConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MiniJavaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int IF = 1;
  /** RegularExpression Id. */
  int ELSE = 2;
  /** RegularExpression Id. */
  int WHILE = 3;
  /** RegularExpression Id. */
  int RETURN = 4;
  /** RegularExpression Id. */
  int NEW = 5;
  /** RegularExpression Id. */
  int CLASS = 6;
  /** RegularExpression Id. */
  int PUBLIC = 7;
  /** RegularExpression Id. */
  int STATIC = 8;
  /** RegularExpression Id. */
  int VOID = 9;
  /** RegularExpression Id. */
  int MAIN = 10;
  /** RegularExpression Id. */
  int LENGTH = 11;
  /** RegularExpression Id. */
  int THIS = 12;
  /** RegularExpression Id. */
  int STRING = 13;
  /** RegularExpression Id. */
  int EXTENDS = 14;
  /** RegularExpression Id. */
  int PRINTLN = 15;
  /** RegularExpression Id. */
  int TRUE = 16;
  /** RegularExpression Id. */
  int FALSE = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int CHAR = 19;
  /** RegularExpression Id. */
  int LBRACE = 20;
  /** RegularExpression Id. */
  int RBRACE = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int LBRACKET = 24;
  /** RegularExpression Id. */
  int RBRACKET = 25;
  /** RegularExpression Id. */
  int SEMICOLON = 26;
  /** RegularExpression Id. */
  int DOT = 27;
  /** RegularExpression Id. */
  int COMMA = 28;
  /** RegularExpression Id. */
  int ASSIGN = 29;
  /** RegularExpression Id. */
  int GT = 30;
  /** RegularExpression Id. */
  int LT = 31;
  /** RegularExpression Id. */
  int BANG = 32;
  /** RegularExpression Id. */
  int AND = 33;
  /** RegularExpression Id. */
  int PLUS = 34;
  /** RegularExpression Id. */
  int MINUS = 35;
  /** RegularExpression Id. */
  int TIMES = 36;
  /** RegularExpression Id. */
  int INTARRAY = 37;
  /** RegularExpression Id. */
  int INT = 38;
  /** RegularExpression Id. */
  int BOOL = 39;
  /** RegularExpression Id. */
  int ID = 40;
  /** RegularExpression Id. */
  int NUM = 41;
  /** RegularExpression Id. */
  int REAL = 42;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int LINE_COMMENT = 1;
  /** Lexical state. */
  int MULTI_COMMENT = 2;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"if\"",
    "\"else\"",
    "\"while\"",
    "\"return\"",
    "\"new\"",
    "\"class\"",
    "\"public\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"length\"",
    "\"this\"",
    "\"String\"",
    "\"extends\"",
    "\"System.out.println\"",
    "\"true\"",
    "\"false\"",
    "<DIGIT>",
    "<CHAR>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\";\"",
    "\".\"",
    "\",\"",
    "\"=\"",
    "\">\"",
    "\"<\"",
    "\"!\"",
    "\"&&\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"int[]\"",
    "\"int\"",
    "\"boolean\"",
    "<ID>",
    "<NUM>",
    "<REAL>",
    "\"//\"",
    "\"/*\"",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "<token of kind 48>",
    "<token of kind 49>",
    "\"*/\"",
    "<token of kind 51>",
    "\".length\"",
  };

}
